### ISSUE TITLE
DNS Pointer

### ISSUE THREAD

**Issue by tjcrone** [real-time-earth/rte-website#1]
@rabernat, it looks like the DNS change has propagated, however it's not clear to me that the correct repo is showing up. The reason is that the latest merged commits with updates to the links on the intern program page are not showing up. Are we sure that rte.ldeo.columbia.edu is correctly pointing to this repo?

**Comment by rabernat** [comment]
I'm still seeing the original site, which means that it has not propagated.

```
$ dig rte.ldeo.columbia.edu

; <<>> DiG 9.10.6 <<>> rte.ldeo.columbia.edu
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22834
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;rte.ldeo.columbia.edu.		IN	A

;; ANSWER SECTION:
rte.ldeo.columbia.edu.	86400	IN	CNAME	www.ldeo.columbia.edu.
www.ldeo.columbia.edu.	86400	IN	A	129.236.14.15

;; Query time: 39 msec
;; SERVER: 129.236.19.32#53(129.236.19.32)
;; WHEN: Thu Aug 09 14:31:08 EDT 2018
;; MSG SIZE  rcvd: 84
```

If you want to force your computer to see the new site, put the following lines in your `/etc/hosts` file:
```
185.199.108.153 rte.ldeo.columbia.edu
```

**Comment by tjcrone** [comment]
Okay I think maybe some caching has confused things on my side. I'll hang tight. Thanks.
